import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryProvider from "@/app/QueryProvider";
import "./globals.css";
import JenniperSet from "@/app/nextJenniper/JenniperSet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko">
			<JenniperSet />
			<body className={inter.className}>
				<QueryProvider>{children}</QueryProvider>
			</body>
		</html>
	);
}
